import Head from "next/head";
import Navbar from "../components/reusable/NavBar/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Classic Computer || Largest tech accessories shop in Bangladesh
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div>
        <Navbar />
      </div>
    </>
  );
}
