import Head from "next/head";
import Navbar from "../components/reusable/NavBar/Navbar";
import SwiperCore, { Autoplay, Pagination } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import Image from 'next/image'
import Featured from "./Admin/Featured";
import Footer from "../components/reusable/Footer/Footer";

SwiperCore.use([Autoplay]);

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Classic Computer || Largest tech accessories shop in Bangladesh
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div className="w-full h-screen dark:bg-gray-800 bg-white">
        <Navbar />
        {/* <div className="container m-auto mt-10">
          <Swiper
            pagination={{
              dynamicBullets: true,
            }}
            modules={[Pagination]}
            className="mySwiper"
            autoplay={{ delay: 3000 }}
            loop={true}
            speed={300}
            direction="horizontal"
            draggable={true}
          >
            <SwiperSlide>
              <Image src={'/assets/Slider/1.png'} alt={"Slider"} width={500} height={250} />
            </SwiperSlide>
            <SwiperSlide>
              <Image src={'/assets/Slider/2.jpg'} alt={"Slider"}  width={500} height={250} />
            </SwiperSlide>
            <SwiperSlide>
              <Image src={'/assets/Slider/3.jpg'} alt={"Slider"} width={500} height={250} />
            </SwiperSlide>
          </Swiper>
        </div> */}
        <Featured/>
        <Footer/>
      </div>
    </>
  );
}
